_posts/google-analytics.md

For the upcoming release of moving GA out of labs and into the app.

Update GA documentation

---

_posts/player-api.md

@mrdavidjcole how does this look? HELLA FLY??

remove outdated reference to iframe api script

---

_posts/audience-engagement-graph.md
_posts/captions.md
_posts/customizing-your-video.md
_posts/embed-shepherd.md
_posts/embedded-video-analytics.md
_posts/identity-tagging.md
_posts/mailchimp.md
_posts/plans-comparison.md
_posts/stats-api.md
_posts/turnstile.md
_posts/wistia-basics-customization.md

This is just a first draft of potential changes (obviously we still need screenshots, etc), but thought I'd get something together.
What else do we need? Get at me!

update timed events/contown customize take 1

---

_posts/captions.md
_posts/customizing-your-video.md
_posts/data-api.md

Just updating some wording and screenshots for the multilingual captions launch. This is specifically in the Customizing Your Video docs. I'm not in love with the wording, so check it out/comment if you want.

updating customize section for multilingual captions launch

---

_posts/captions.md
_posts/customizing-your-video.md
_posts/data-api.md

Revert "updating customize section for multilingual captions launch"

---

_posts/captions.md

this is just a screenshot update, but is also restoring this branch for when we're good to launch.

update docs for multilingual captions

---

_posts/embed-links.md

@emilywistia @jordanmunson  I don't think this page is quite done yet, but is it all right if I push it live so we can refer to it? This is documentation for embed links and playlist links, to live at /doc/embed-links.

Mms embed links

---

_posts/embedded-video-analytics.md

Update the copy within the docs to account for new Trends Page updates.

Trends Page Updates!

---

_posts/export-settings.md
_posts/exporting-guide.md
_posts/upload-troubleshooting.md
_posts/upload-video.md

Should be solid, but if anyone wants to give me feedback it's NOW OR NEVER.

Update Docs for HTML5 Uploader 🚁

---

_posts/bandwidth.md

It's a bird, it's a plane -- NO IT'S THE BANDWIDTH PAGE.

Bandwidth Page of Awesome Epicness 🔥

---

_posts/hubspot.md
_posts/marketo.md
_posts/pardot.md
_posts/turnstile.md

Update screenshots and instructions to account for new "Data Integrations" page in Account Settings.

Update Integrations Pages for Data Integrations UI Update

---

README.md
_includes/haml/doc_nav.haml
_layouts/haml/base.haml
_layouts/haml/search.haml
_sass/_search.sass
_static_pages/index.haml
index.html
javascripts/jquery.ba-hashchange.min.js
javascripts/jquery.swiftype.autocomplete.js
javascripts/jquery.swiftype.search.js
sample_swiftype.html

**HALP!**
I can't for the life of me get the CSS to look good. Swiftype makes the input field look a certain way and I cannot get rid of that damn magnifying glass they add.... or at least pad the text to the right of it.

Swiftype Search on Da Docs

---

README.md
_includes/haml/doc_nav.haml
_layouts/haml/base.haml
_layouts/haml/search.haml
_sass/_search.sass
_static_pages/index.haml
index.html
javascripts/jquery.ba-hashchange.min.js
javascripts/jquery.swiftype.autocomplete.js
javascripts/jquery.swiftype.search.js
sample_swiftype.html

* Included Swiftype libraries to site
* Test page
* Add Swiftype to small search input field
* Add Swiftype results container to search results page.
* Add Swiftype to main search input field
* Removed Wistia style... just surrend to Swiftype's
* Remove search buttons
* Use Swiftype meta tag format
* Added proper meta tags
* Added new search engine installer

Swiftype Search

---

README.md

update readme to include that you need to install Cask too! WOO!

add note about cask

---

_posts/google-analytics.md

Updating doc to reflect reality @emilyscoleman

Add __gaTracker to tracker names

---

_sass/_post_content.sass
stylesheets/screen.css

Before:
After: 
@emilyscoleman - this cool?

Make links look prettier when they appear in Tip boxes

---

_posts/data-api.md

While trying to access the Wisita API for a client to get video stats, ran into some confusion about API password. I feel this is clearer! Thanks for taking time to review!

Update data-api doc about api-password for requests

---

_posts/embedded-video-analytics.md

This branch replaces this bad boy (https://github.com/wistia/wistia-doc/pull/226).
Am currently in-process for this update, but I'm doing a rewrite of the embedded-video-analytics page since it's a bit stale and kind of dense. I'll also loop in updating the audience-engagement-graph screenshots and some sprucing of the identity-tagging, private-sharing, and private-analytics pages.

View Stream Heatmaps Launch Prep

---

_posts/player-api.md

Just list the "end" event for the player api and include console.log message from Lenny.

add "end" to list of events for player api

---

_posts/player-api.md

we should head this Standard embeds.
@emilyscoleman

Update heading to refer to standard embeds

---

_layouts/haml/base.haml
_sass/_categories_pages.sass
_sass/_index_page.sass
_sass/_post_content.sass
_sass/_search.sass
_sass/_vars_and_mixins.sass
_sass/screen.sass

Let's get the Help Pages on par with the rest of wistiacom, and get Whitney as the official font! :dancer:
@liatwerber is helping with this one!

Bring the Help Pages into the 21st Century

---

_posts/integrations.md

You can also embed Wistia videos in an app called Project Manager! 
@emilyscoleman oh gawd am I doing this right?

Add Project Manager to integrations list

---

_posts/integrations.md

Link to Project Manager's integrations page - https://www.projectmanager.com/integrations-more

Add link to Project Manager

---

_posts/player-api.md

@emilyscoleman I snuck in another bracket in here :) Please merge in.

add a missing bracket

---

_posts/bandwidth.md

This is the beginning of updating the Bandwidth page for detangling.
Still to do: 
- change the word "overage" to something else throughout
- update the Conversion Chart with the right math for detangled bandwidth
- high five everyone I know on account of I just made my first real pull request WHAT'S UP

Starting to bring the Bandwidth page up to speed wrt detangled bandwidth

---

_posts/marketo.md

Changing over from blue note to yellow alert!
@emilyscoleman @laurendelench

change note to alert style

---

_posts/stats-api.md

https://secure.helpscout.net/conversation/146991664/168768/?folderId=610
https://secure.helpscout.net/conversation/148365769/169281/?folderId=606

Update stats-api.md to reflect percent_viewed as a decimal number

---

_posts/data-api.md

Update medias#update method to indicate acceptable description formats (plain text, markdown).
Documents https://github.com/wistia/wistia/pull/2021

Update data api to indicate acceptable description formats.

---

_posts/stats-api.md

Documenting some changes we made to Visitor#List and Visitor#Show.
Added a filter in list to return only turnstile entries.
Added more visitor_identity info.
Added user_agent_details.

Documenting some stats API changes from adding turnstile filter and clearbit data

---

_posts/embedded-video-analytics.md

We're getting an Audience page! This is the PR that gets the Help Pages ready for the launch of that feature.

Embedded Video Analytics Update for Audience Page

---

_posts/customizing-your-video.md
_posts/social-sharing.md

I've updated the Social Sharing to have a FB Like section. It has an example using Jeff's Lemonade. May need a little styling. @emilyscoleman

Jay-updating-FB-like

---

_posts/updating-your-popover-embeds.md

@emilyscoleman @fordanthony I was educating myself about the popover embed update that's happening soon, and noticed a couple things to fix in the updating guide. The straightforward typo/grammar things are already changed here, but there are a couple other things that we might want to modify:
1. **"While the codes are different, the popover player works the exact same way."** There are actually a bunch of differences! Thinking of things like the automatic resizing of the video, and the hover behavior of the thumbnail.
2. The screenshot at http://wistia.com/doc/updating-your-popover-embeds#how_to_update_your_embeds doesn't match our typical screenshot style (the border).
3. **"This way all of the files are served directly by Wistia, rather than an external CDN"** Is that factual? If so, …

Fix a couple typos and grammatical errors, plus some tiny style tweaks

---

_posts/updating-your-popover-embeds.md

@mrdavidjcole @emilyscoleman made a couple of tweaks.

fix dave notes

---

_posts/embed-options.md

This time I made sure I didn't copy incorrectly beautified brackets, and found some more brackets that needed adding. The code blocks should all work now for the Player API. @emilyscoleman

JH fixing brackets round 2

---

_posts/social-sharing.md

Title says it all. Tried to make it a little less technical sounding and more coloquial @emilyscoleman

create social sharing section on the FB debugger

---

_posts/integrations.md

Per Luis' suggestion! @emilyscoleman

Add enterprise notes to turnstile list

---

_posts/email-marketing.md

Addresses https://github.com/wistia/wistia-doc/issues/123. @emilyscoleman

add note to dynamic links and small tweaks

---

_posts/hubspot.md

This addresses #206. Look OK to you, @emilyscoleman?

Add hubspot troubleshooting alert

---

_posts/turnstile.md

Update Turnstile integration screenshots and tiny copy tweaks

---

_posts/account-setup.md

Partially addresses #238. 
@emilyscoleman There are a few other screenshots in here that show the outdated sidebar. Think it's worth updating these as well?

Add integrations and beta sections to account setup

---

_posts/wordpress.md

move plugin down, tweak a few words, and update screencast

---

_posts/embedded-video-analytics.md

This PR is for the design updates to the trends page.

Analytics Updates

---

_posts/integrations.md

@emilyscoleman 
re: https://github.com/wistia/wistia/issues/2088

Add SmartFocus to email campaign list

---

_posts/working-with-images.md

Fix a typo
